### ISSUE TITLE
Error finding module when reading bundle

### ISSUE THREAD

**Issue by silverbucket** [wanadev/browserify-licenses#15]
This error is a bit obscure, not sure what it means by trying to find a module `./sync-event`. There is nothing in `node_modules/` by the name of `sync-event` and not sure where it is or what it's trying to do (look in the local build directory for another file?)

```
$ brlicenses build/bundle.js
{ Error: Cannot find module './sync-event' from '/project/build'
    at /usr/local/lib/node_modules/browserify-licenses/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify-licenses/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify-licenses/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify-licenses/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:112:15)
  stream: 
   Labeled {
     _readableState: 
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: [Object],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object], [Object] ],
     length: 2,
     label: 'deps' } }
```

**Comment by silverbucket** [comment]
A bit of extra information, if I `grep` the projects source code for `sync-event` I get no results, but if I grep the bundle created from the projects source code, I do see references to `sync-event` but they seem to in reference to the `ts-events` npm module. Have you tried `brlicenses` with the `ts-events` module before? Could it be something there confuses `brlicenses`?

**Comment by flozz** [comment]
Hello,

**browserify-licenses** is not able to extract the licenses from the bundled js but from the original source code entry point. Try something like:

    brlicenses app/index.js

(replacing `app/index.js` by your entry point) :)

**Comment by silverbucket** [comment]
Ah I see, it's clear now, but actually it's not totally clear from reading the docs. You mention the 'bundle' in the readme:
```
--browserify, -b  Extract licenses used in a bundle using Browserify to find
                      included modules (this option can be ommited)
```

But aside from that, the code I'm working with is all written in TypeScript. Is there any way to use this with TypeScript code?

**Comment by flozz** [comment]
I have to add support for Browserify's tranforms to allow everything supported by Browserify to work wi this software

**Comment by silverbucket** [comment]
@flozz Any idea if you'll be able to do this sometime soon? Or are these someday/maybe plans?

**Comment by flozz** [comment]
I have no time to do it currently... so it is a someday/maybe plan :sweat:
